
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoyo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yoyo-operator
  template:
    metadata:
      labels:
        name: yoyo-operator
    spec:
      serviceAccountName: yoyo-operator
      containers:
        - name: yoyo-operator
          image: quay.io/jdzon/yoyo-operator:latest
          command:
          - yoyo-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "yoyo-operator"
